<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome To My New Page</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

   	<!-- Main Theme -->
    <link type="text/css" rel="stylesheet" href="/css/style.css">
  
  </head>
  <body>
    <div>
			<nav>
				<ul>
          <li><a href="/index">Principal </a></li>
          <li><a href="/car">Autos </a></li>
				</ul>
			</nav>
			
